### ISSUE TITLE
numpy.int deprecated, using numpy 1.24.3

### ISSUE THREAD

**Issue by haraQQiri** [brisvag/cs2star#2]
Hello, 

getting an error from numpy with attribute int, maybe needs to change to just int?

**Comment by brisvag** [comment]
Hi @haraQQiri, thanks for opening the issue; I don't use `np.int` anywhere in my code, so this must be from the dependency of `pyem`. I updated it on my my branch, so you can reinstall it and hopefully it'll stop warning you.

```
pip install git+https://github.com/brisvag/pyem.git
```
