### ISSUE TITLE
ValueError: Number of passthrough files and particle files is incompatible

### ISSUE THREAD

**Issue by helgepat** [brisvag/cs2star#3]
Hi,

I am trying to set up my pipeline:
a) MotionCorr in Relion
b) Extraction of particles in Relion
c) Transfer to Cryosparc
d) 2D classification in Cryosparc
e) Transfer of good particles back to Relion

I am facing an issue at step e) when I run cs2star on the selection job after 2D classification in Cryosparc (also if I run a homoegeneous refinement and then run cs3star on that).

The error is shown below, I am not sure if I set everything up correctly in Cryosparc. 
First, I imported the micrographs from Relion setting the full path to the MotionCorr folder of Relion and using a wildcard for the micrographs (/home/etc/MotionCorr/job002/RawMovies/*.mrc)
Then, I imported my particles from Relion particles.star, specifying the imported micrographs in Cryosparc while removing the UID.
After 2D classification in Cryosparc, I selected one class and then ran cs2star on the corrsponding job folder.

This gives me the error message below, could you maybe tell me if I am doing something incorrectly and point me in the rightr direction to make this work?

<pre>Traceback (most recent call last):
  File &quot;/home/agwilson/Software/miniconda3/envs/pyem/bin/cs2star&quot;, line 8, in &lt;module&gt;
    sys.exit(main())
  File &quot;/home/agwilson/Software/miniconda3/envs/pyem/lib/python3.10/site-packages/click/core.py&quot;, line 1130, in __call__
    return self.main(*args, **kwargs)
  File &quot;/home/agwilson/Software/miniconda3/envs/pyem/lib/python3.10/site-packages/click/core.py&quot;, line 1055, in main
    rv = self.invoke(ctx)
  File &quot;/home/agwilson/Software/miniconda3/envs/pyem/lib/python3.10/site-packages/click/core.py&quot;, line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File &quot;/home/agwilson/Software/miniconda3/envs/pyem/lib/python3.10/site-packages/click/core.py&quot;, line 760, in invoke
    return __callback(*args, **kwargs)
  File &quot;/home/agwilson/Software/miniconda3/envs/pyem/lib/python3.10/site-packages/cs2star/cs2star.py&quot;, line 136, in main
    raise ValueError(&apos;Number of passthrough files and particle files is incompatible&apos;)
ValueError: Number of passthrough files and particle files is incompatible
</pre>

**Comment by brisvag** [comment]
Hi @helgepat! I think I saw this before, and maybe even fixed it. Can you make sure to run on the latest cs2star version and report back if it works?

**Comment by helgepat** [comment]
Hey,
I just removed the conda environment and re-installed pyem and cs2star, unfortunately the issue is still there...

**Comment by brisvag** [comment]
Could try to install cs2star from the branch in #4? You can do it with:

```
pip install git+git://github.com/brisvag/cs2star.git@fix/wrong-number-passwthough#egg=cs2star
```

This should for now at least give more informative errors.

**Comment by helgepat** [comment]
This is the message I get with the version you specified:

`cs2star J45 CS2STAR/J45 -p
Traceback (most recent call last):
  File "/home/agwilson/Software/miniconda3/envs/pyem/bin/cs2star", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/agwilson/Software/miniconda3/envs/pyem/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/agwilson/Software/miniconda3/envs/pyem/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/agwilson/Software/miniconda3/envs/pyem/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/agwilson/Software/miniconda3/envs/pyem/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/agwilson/Software/miniconda3/envs/pyem/lib/python3.11/site-packages/cs2star/cs2star.py", line 140, in main
    raise ValueError(
ValueError: Number of passthrough files and micrographs files is incompatible:
micrographs: [PosixPath('/home/agwilson/XxX-CS/J45/J45_passthrough_particles_selected.cs')]
passthroughs: [PosixPath('/home/agwilson/XxX-CS/J45/J45_passthrough_particles_selected.cs')]`

**Comment by brisvag** [comment]
I'm sorry, I was a bit hasty and did that change wrong ^^' could you reinstall and try again?
I might have find the issue anyways... Let's see if this works!

Sorry for the back and forth, this stuff is tricky to debug without direct access or a reproducible case!

**Comment by helgepat** [comment]
I just re-installed and here is the message:

cs2star J45 CS2STAR/J45 -p
Traceback (most recent call last):
  File "/home/agwilson/Software/miniconda3/envs/pyem/bin/cs2star", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/agwilson/Software/miniconda3/envs/pyem/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/agwilson/Software/miniconda3/envs/pyem/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/agwilson/Software/miniconda3/envs/pyem/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/agwilson/Software/miniconda3/envs/pyem/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/agwilson/Software/miniconda3/envs/pyem/lib/python3.11/site-packages/cs2star/cs2star.py", line 144, in main
    raise ValueError(
ValueError: Number of passthrough files and micrographs files is incompatible:
micrographs: [PosixPath('/home/agwilson/XxX-CS/J12/imported_micrographs.cs')]
passthroughs: []


I think, I have the newest version because;

conda list | grep cs2star
cs2star                   0.5.5.dev2+g3b1390c          pypi_0    pypi


Maybe, I set up the import in the wrong way?

**Comment by brisvag** [comment]
Nope, once again my bad, may be good now!

**Comment by helgepat** [comment]
That seems to have done it, I get output files, still have to verify those in Relion.

I noticed that the image-names and micrograph-names in particles.star are routed through symlinks, why is this necessary? Also: I should be able to re-extract the particles in Relion following this procdure?

Many thanks for the fixes!

**Comment by brisvag** [comment]
Nice! I will merge and push a release then.

The symlink/copy option is needed because cryosparc uses `mrc` instead of `mrcs` for stack files, and relion doesn't like that. At least, it was the case last time I checked. You'll see that all the symlink end in `mrcs` while the original files in `mrc`. Without symlinks, you'd have to either copy all the data, or rename it and make it unreachable from cryosparc.

Yes, you should be able to just reextract, but let me know if if you have other issues!
